### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by fstamour** [Dimercel/listopia#1]
Hello, that looks like a nice library, but I was wondering why one would want to use it?
Could you add a little something in the readme that explains what are the advantages of this library, and/or what problem does it solve.

I'm genuinely curious :)

(sorry for the bad issue title)

**Comment by Dimercel** [comment]
Hello, thanks for question. My main motive is more functional interface of Data.List and absence of some needed functions in CL. Maybe their number increase, with time.
  I'm will add description in future releases.
