### ISSUE TITLE
Why do all function names start with dots?

### ISSUE THREAD

**Issue by svetlyak40wt** [Dimercel/listopia#3]
This seems somewhat non-lispy. Is there a reason?

**Comment by Dimercel** [comment]
There is no big technical reason for this. This is done for easy import and no conflicts with names from other packages.

**Comment by maruks** [comment]
I am not going to use a library where all functions start with a dot. It looks like Java interop in Clojure. Lisp has packages: https://lispcookbook.github.io/cl-cookbook/packages.html

**Comment by vindarel** [comment]
Hi Dimercel, I also think it is unfortunate. I think not `use`ing listopia but calling functions with their callified name is already fine (`listopia:scanl)` etc. You can maybe make good use of a short package nickname.

Another reaction:

> Isn't the whole point of packages so that this kind of thing is unnecessary?
> you could simply include two packages in your library, "listopia" and "listopia-dotted" which re-exports the original functions under dotted names. Then let the user choose which one they want to import.

**Comment by Dimercel** [comment]
> you could simply include two packages in your library, "listopia" and "listopia-dotted" which re-exports the original functions under dotted names. Then let the user choose which one they want to import.

I think this will lead to unnecessary complexity. I agree to leave one package with no dots names. I will work on this in the next release.

**Comment by vindarel** [comment]
Nice, thank you :)
